name = "tyche-do"
main = "src/index.ts"
node_compat = true
compatibility_date = "2023-03-12"

[durable_objects]
bindings = [
  { name = "INDEXER", class_name = "Indexer" },
  { name = "USER_BOARDSETS", class_name = "UserBoardsets" },
  { name = "USERS", class_name = "Users" },
]

[[migrations]]
tag = "v1"
new_classes = ["Users"]

[[migrations]]
tag = "v2"
new_classes = ["Indexer"]

[[migrations]]
tag = "v3"
new_classes = ["UserBoardsets"]

