name = "tyche-do"
main = "src/index.ts"
node_compat = true
compatibility_date = "2023-03-12"

[durable_objects]
bindings = [
  { name = "USERS", class_name = "Users" },
]

[[migrations]]
tag = "v1"
new_classes = ["Users"]
