name = "tyche-do-sveltehack"
main = "src/index.ts"
node_compat = true
compatibility_date = "2023-03-27"

[durable_objects]
bindings = [
  { name = "BOARD", class_name = "Board" },
  { name = "BOARDSET_BOARDS", class_name = "BoardsetBoards" },
  { name = "INDEXER", class_name = "Indexer" },
  { name = "USER_BOARDSETS", class_name = "UserBoardsets" },
  { name = "USER_SETTINGS", class_name = "UserSettings" },
  { name = "USERS", class_name = "Users" },
]

[[migrations]]
tag = "v1"
new_classes = ["Board", "BoardsetBoards", "Indexer", "UserBoardsets", "UserSettings", "Users"]
